"""
50 Chinese radicals with examples, pinyin, meanings (EN + RU)
"""

RADICALS = [
    {"id":"r01","radical":"氵","full":"水","pinyin":"shuǐ","meaning_en":"water","meaning_ru":"вода","example":"河","ex_pinyin":"hé","ex_en":"river"},
    {"id":"r02","radical":"扌","full":"手","pinyin":"shǒu","meaning_en":"hand","meaning_ru":"рука","example":"打","ex_pinyin":"dǎ","ex_en":"to hit"},
    {"id":"r03","radical":"亻","full":"人","pinyin":"rén","meaning_en":"person","meaning_ru":"человек","example":"你","ex_pinyin":"nǐ","ex_en":"you"},
    {"id":"r04","radical":"忄","full":"心","pinyin":"xīn","meaning_en":"heart; feelings","meaning_ru":"сердце; чувства","example":"情","ex_pinyin":"qíng","ex_en":"feeling"},
    {"id":"r05","radical":"讠","full":"言","pinyin":"yán","meaning_en":"speech; word","meaning_ru":"речь; слово","example":"说","ex_pinyin":"shuō","ex_en":"to speak"},
    {"id":"r06","radical":"口","full":"口","pinyin":"kǒu","meaning_en":"mouth","meaning_ru":"рот","example":"吃","ex_pinyin":"chī","ex_en":"to eat"},
    {"id":"r07","radical":"木","full":"木","pinyin":"mù","meaning_en":"tree; wood","meaning_ru":"дерево","example":"桥","ex_pinyin":"qiáo","ex_en":"bridge"},
    {"id":"r08","radical":"日","full":"日","pinyin":"rì","meaning_en":"sun; day","meaning_ru":"солнце; день","example":"晴","ex_pinyin":"qíng","ex_en":"sunny"},
    {"id":"r09","radical":"月","full":"月","pinyin":"yuè","meaning_en":"moon; month","meaning_ru":"луна; месяц","example":"期","ex_pinyin":"qī","ex_en":"period"},
    {"id":"r10","radical":"女","full":"女","pinyin":"nǚ","meaning_en":"woman","meaning_ru":"женщина","example":"妈","ex_pinyin":"mā","ex_en":"mother"},
    {"id":"r11","radical":"子","full":"子","pinyin":"zǐ","meaning_en":"child; son","meaning_ru":"ребёнок; сын","example":"孩","ex_pinyin":"hái","ex_en":"child"},
    {"id":"r12","radical":"山","full":"山","pinyin":"shān","meaning_en":"mountain","meaning_ru":"гора","example":"岩","ex_pinyin":"yán","ex_en":"rock"},
    {"id":"r13","radical":"土","full":"土","pinyin":"tǔ","meaning_en":"earth; soil","meaning_ru":"земля; почва","example":"地","ex_pinyin":"dì","ex_en":"ground"},
    {"id":"r14","radical":"灬","full":"火","pinyin":"huǒ","meaning_en":"fire","meaning_ru":"огонь","example":"灯","ex_pinyin":"dēng","ex_en":"lamp"},
    {"id":"r15","radical":"石","full":"石","pinyin":"shí","meaning_en":"stone","meaning_ru":"камень","example":"硬","ex_pinyin":"yìng","ex_en":"hard"},
    {"id":"r16","radical":"钅","full":"金","pinyin":"jīn","meaning_en":"metal; gold","meaning_ru":"металл; золото","example":"钟","ex_pinyin":"zhōng","ex_en":"clock"},
    {"id":"r17","radical":"饣","full":"食","pinyin":"shí","meaning_en":"food; to eat","meaning_ru":"еда","example":"饭","ex_pinyin":"fàn","ex_en":"rice; meal"},
    {"id":"r18","radical":"衤","full":"衣","pinyin":"yī","meaning_en":"clothing","meaning_ru":"одежда","example":"裤","ex_pinyin":"kù","ex_en":"trousers"},
    {"id":"r19","radical":"车","full":"车","pinyin":"chē","meaning_en":"vehicle; car","meaning_ru":"машина; транспорт","example":"辆","ex_pinyin":"liàng","ex_en":"(counter for vehicles)"},
    {"id":"r20","radical":"门","full":"门","pinyin":"mén","meaning_en":"door; gate","meaning_ru":"дверь; ворота","example":"问","ex_pinyin":"wèn","ex_en":"to ask"},
    {"id":"r21","radical":"宀","full":"宀","pinyin":"mián","meaning_en":"roof","meaning_ru":"крыша","example":"家","ex_pinyin":"jiā","ex_en":"home"},
    {"id":"r22","radical":"艹","full":"艸","pinyin":"cǎo","meaning_en":"grass; plants","meaning_ru":"трава; растения","example":"草","ex_pinyin":"cǎo","ex_en":"grass"},
    {"id":"r23","radical":"辶","full":"辵","pinyin":"chuò","meaning_en":"movement; walk","meaning_ru":"движение; идти","example":"近","ex_pinyin":"jìn","ex_en":"near"},
    {"id":"r24","radical":"彳","full":"彳","pinyin":"chì","meaning_en":"step; walk slowly","meaning_ru":"шаг; идти медленно","example":"很","ex_pinyin":"hěn","ex_en":"very"},
    {"id":"r25","radical":"足","full":"足","pinyin":"zú","meaning_en":"foot; sufficient","meaning_ru":"нога; достаточно","example":"跑","ex_pinyin":"pǎo","ex_en":"to run"},
    {"id":"r26","radical":"犭","full":"犬","pinyin":"quǎn","meaning_en":"dog; animal","meaning_ru":"собака; животное","example":"狗","ex_pinyin":"gǒu","ex_en":"dog"},
    {"id":"r27","radical":"鸟","full":"鳥","pinyin":"niǎo","meaning_en":"bird","meaning_ru":"птица","example":"鸭","ex_pinyin":"yā","ex_en":"duck"},
    {"id":"r28","radical":"鱼","full":"魚","pinyin":"yú","meaning_en":"fish","meaning_ru":"рыба","example":"鲜","ex_pinyin":"xiān","ex_en":"fresh"},
    {"id":"r29","radical":"虫","full":"虫","pinyin":"chóng","meaning_en":"insect; worm","meaning_ru":"насекомое","example":"蛛","ex_pinyin":"zhū","ex_en":"spider"},
    {"id":"r30","radical":"耳","full":"耳","pinyin":"ěr","meaning_en":"ear","meaning_ru":"ухо","example":"聊","ex_pinyin":"liáo","ex_en":"to chat"},
    {"id":"r31","radical":"目","full":"目","pinyin":"mù","meaning_en":"eye","meaning_ru":"глаз","example":"眼","ex_pinyin":"yǎn","ex_en":"eye"},
    {"id":"r32","radical":"贝","full":"貝","pinyin":"bèi","meaning_en":"shell; money","meaning_ru":"раковина; деньги","example":"购","ex_pinyin":"gòu","ex_en":"to buy"},
    {"id":"r33","radical":"力","full":"力","pinyin":"lì","meaning_en":"strength; force","meaning_ru":"сила","example":"加","ex_pinyin":"jiā","ex_en":"to add"},
    {"id":"r34","radical":"工","full":"工","pinyin":"gōng","meaning_en":"work; labor","meaning_ru":"работа; труд","example":"功","ex_pinyin":"gōng","ex_en":"merit"},
    {"id":"r35","radical":"米","full":"米","pinyin":"mǐ","meaning_en":"rice; grain","meaning_ru":"рис; зерно","example":"粮","ex_pinyin":"liáng","ex_en":"grain"},
    {"id":"r36","radical":"⺮","full":"竹","pinyin":"zhú","meaning_en":"bamboo","meaning_ru":"бамбук","example":"箱","ex_pinyin":"xiāng","ex_en":"box"},
    {"id":"r37","radical":"纟","full":"糸","pinyin":"mì","meaning_en":"thread; silk","meaning_ru":"нить; шёлк","example":"级","ex_pinyin":"jí","ex_en":"level"},
    {"id":"r38","radical":"王","full":"王","pinyin":"wáng","meaning_en":"king; ruler","meaning_ru":"царь; король","example":"玩","ex_pinyin":"wán","ex_en":"to play"},
    {"id":"r39","radical":"玉","full":"玉","pinyin":"yù","meaning_en":"jade; gem","meaning_ru":"нефрит; драгоценность","example":"珠","ex_pinyin":"zhū","ex_en":"pearl"},
    {"id":"r40","radical":"疒","full":"疒","pinyin":"nè","meaning_en":"illness; sickbed","meaning_ru":"болезнь","example":"病","ex_pinyin":"bìng","ex_en":"illness"},
    {"id":"r41","radical":"广","full":"广","pinyin":"guǎng","meaning_en":"shelter; wide space","meaning_ru":"навес; широкое помещение","example":"店","ex_pinyin":"diàn","ex_en":"shop"},
    {"id":"r42","radical":"刂","full":"刀","pinyin":"dāo","meaning_en":"knife; blade","meaning_ru":"нож","example":"刚","ex_pinyin":"gāng","ex_en":"just now; firm"},
    {"id":"r43","radical":"雨","full":"雨","pinyin":"yǔ","meaning_en":"rain","meaning_ru":"дождь","example":"零","ex_pinyin":"líng","ex_en":"zero; drops"},
    {"id":"r44","radical":"风","full":"風","pinyin":"fēng","meaning_en":"wind","meaning_ru":"ветер","example":"飘","ex_pinyin":"piāo","ex_en":"to flutter"},
    {"id":"r45","radical":"囗","full":"囗","pinyin":"wéi","meaning_en":"enclosure; frame","meaning_ru":"ограда; рамка","example":"国","ex_pinyin":"guó","ex_en":"country"},
    {"id":"r46","radical":"大","full":"大","pinyin":"dà","meaning_en":"big; large","meaning_ru":"большой","example":"奇","ex_pinyin":"qí","ex_en":"strange"},
    {"id":"r47","radical":"小","full":"小","pinyin":"xiǎo","meaning_en":"small; little","meaning_ru":"маленький","example":"少","ex_pinyin":"shǎo","ex_en":"few"},
    {"id":"r48","radical":"白","full":"白","pinyin":"bái","meaning_en":"white","meaning_ru":"белый","example":"的","ex_pinyin":"de","ex_en":"(particle)"},
    {"id":"r49","radical":"黑","full":"黑","pinyin":"hēi","meaning_en":"black","meaning_ru":"чёрный","example":"墨","ex_pinyin":"mò","ex_en":"ink"},
    {"id":"r50","radical":"马","full":"馬","pinyin":"mǎ","meaning_en":"horse","meaning_ru":"лошадь","example":"驴","ex_pinyin":"lǘ","ex_en":"donkey"},
]
