# sentences.py - fill-in-the-blank sentences tagged by grammar point
# Each: sentence (with target word), translation, hsk, grammar (tag matching GRAMMAR_POINTS)

SENTENCES = [
    # ---- HSK 1: basic SVO, 是, 有, 很+adj ----
    {"sentence":"我是学生。","translation":"I am a student.","hsk":1,"grammar":"shi_to_be"},
    {"sentence":"他是老师。","translation":"He is a teacher.","hsk":1,"grammar":"shi_to_be"},
    {"sentence":"这是我的书。","translation":"This is my book.","hsk":1,"grammar":"de_possessive"},
    {"sentence":"那是你的杯子。","translation":"That is your cup.","hsk":1,"grammar":"de_possessive"},
    {"sentence":"我有一个朋友。","translation":"I have a friend.","hsk":1,"grammar":"you_have"},
    {"sentence":"她有两个孩子。","translation":"She has two children.","hsk":1,"grammar":"you_have"},
    {"sentence":"今天很热。","translation":"Today is very hot.","hsk":1,"grammar":"hen_adj"},
    {"sentence":"这个菜很好吃。","translation":"This dish is delicious.","hsk":1,"grammar":"hen_adj"},
    {"sentence":"我喜欢喝茶。","translation":"I like to drink tea.","hsk":1,"grammar":"svo_basic"},
    {"sentence":"我们去学校。","translation":"We go to school.","hsk":1,"grammar":"svo_basic"},
    {"sentence":"你叫什么名字？","translation":"What is your name?","hsk":1,"grammar":"question_what"},
    {"sentence":"现在几点？","translation":"What time is it now?","hsk":1,"grammar":"question_what"},
    {"sentence":"我不是中国人。","translation":"I am not Chinese.","hsk":1,"grammar":"bu_negation"},
    {"sentence":"他不喝咖啡。","translation":"He doesn't drink coffee.","hsk":1,"grammar":"bu_negation"},
    {"sentence":"你好吗？","translation":"How are you?","hsk":1,"grammar":"ma_question"},
    {"sentence":"你是医生吗？","translation":"Are you a doctor?","hsk":1,"grammar":"ma_question"},

    # ---- HSK 2: 了, 在+verb, 比, 想/要, 因为...所以 ----
    {"sentence":"我吃了饭。","translation":"I have eaten.","hsk":2,"grammar":"le_completed"},
    {"sentence":"他买了一本书。","translation":"He bought a book.","hsk":2,"grammar":"le_completed"},
    {"sentence":"我正在看电视。","translation":"I am watching TV.","hsk":2,"grammar":"zai_progressive"},
    {"sentence":"她在做作业。","translation":"She is doing homework.","hsk":2,"grammar":"zai_progressive"},
    {"sentence":"我比你高。","translation":"I am taller than you.","hsk":2,"grammar":"bi_comparison"},
    {"sentence":"今天比昨天冷。","translation":"Today is colder than yesterday.","hsk":2,"grammar":"bi_comparison"},
    {"sentence":"我想去北京。","translation":"I want to go to Beijing.","hsk":2,"grammar":"xiang_want"},
    {"sentence":"我要喝水。","translation":"I want to drink water.","hsk":2,"grammar":"yao_want"},
    {"sentence":"因为下雨，所以我不去。","translation":"Because it's raining, I won't go.","hsk":2,"grammar":"yinwei_suoyi"},
    {"sentence":"虽然很累，但是很高兴。","translation":"Although tired, I'm happy.","hsk":2,"grammar":"suiran_danshi"},
    {"sentence":"我已经吃过了。","translation":"I have already eaten.","hsk":2,"grammar":"guo_experiential"},
    {"sentence":"我去过中国。","translation":"I have been to China.","hsk":2,"grammar":"guo_experiential"},
    {"sentence":"请给我一杯茶。","translation":"Please give me a cup of tea.","hsk":2,"grammar":"gei_give"},
    {"sentence":"他送给我一个礼物。","translation":"He gave me a gift.","hsk":2,"grammar":"gei_give"},
    {"sentence":"如果你来，我很高兴。","translation":"If you come, I'll be happy.","hsk":2,"grammar":"ruguo_if"},
    {"sentence":"我从北京来。","translation":"I come from Beijing.","hsk":2,"grammar":"cong_from"},

    # ---- HSK 3: 把, 被, 着, 把...complement, 越来越, 一边...一边 ----
    {"sentence":"我把书放在桌子上。","translation":"I put the book on the table.","hsk":3,"grammar":"ba_disposal"},
    {"sentence":"请把门关上。","translation":"Please close the door.","hsk":3,"grammar":"ba_disposal"},
    {"sentence":"我的自行车被偷了。","translation":"My bike was stolen.","hsk":3,"grammar":"bei_passive"},
    {"sentence":"他被老师批评了。","translation":"He was criticized by the teacher.","hsk":3,"grammar":"bei_passive"},
    {"sentence":"门开着。","translation":"The door is open.","hsk":3,"grammar":"zhe_continuous"},
    {"sentence":"他穿着一件红衣服。","translation":"He is wearing red clothes.","hsk":3,"grammar":"zhe_continuous"},
    {"sentence":"天气越来越冷。","translation":"The weather is getting colder and colder.","hsk":3,"grammar":"yuelaiyue"},
    {"sentence":"他的中文越来越好。","translation":"His Chinese is getting better and better.","hsk":3,"grammar":"yuelaiyue"},
    {"sentence":"我一边吃饭一边看电视。","translation":"I eat while watching TV.","hsk":3,"grammar":"yibian_yibian"},
    {"sentence":"她一边走一边唱歌。","translation":"She sings while walking.","hsk":3,"grammar":"yibian_yibian"},
    {"sentence":"只要努力就能成功。","translation":"As long as you work hard, you can succeed.","hsk":3,"grammar":"zhiyao_jiu"},
    {"sentence":"不但聪明，而且认真。","translation":"Not only smart, but also diligent.","hsk":3,"grammar":"budan_erqie"},
    {"sentence":"我是坐地铁来的。","translation":"I came by subway.","hsk":3,"grammar":"shi_de_emphasis"},
    {"sentence":"他是昨天到的。","translation":"It was yesterday that he arrived.","hsk":3,"grammar":"shi_de_emphasis"},
    {"sentence":"这本书比那本有意思。","translation":"This book is more interesting than that one.","hsk":3,"grammar":"bi_comparison"},
    {"sentence":"他跑得很快。","translation":"He runs very fast.","hsk":3,"grammar":"de_complement"},
    {"sentence":"她说得很清楚。","translation":"She speaks very clearly.","hsk":3,"grammar":"de_complement"},
    {"sentence":"我看完了那本书。","translation":"I finished reading that book.","hsk":3,"grammar":"resultative_complement"},
    {"sentence":"我听懂了老师的话。","translation":"I understood the teacher's words.","hsk":3,"grammar":"resultative_complement"},
    {"sentence":"为了学好中文，我每天练习。","translation":"To learn Chinese well, I practice every day.","hsk":3,"grammar":"weile_purpose"},
    {"sentence":"虽然很难，但是我喜欢。","translation":"Although it's hard, I like it.","hsk":3,"grammar":"suiran_danshi"},
    {"sentence":"他不但会说中文，还会写汉字。","translation":"He can not only speak Chinese but also write characters.","hsk":3,"grammar":"budan_erqie"},
    {"sentence":"如果有时间，我就去旅游。","translation":"If I have time, I'll travel.","hsk":3,"grammar":"ruguo_if"},
    {"sentence":"我把作业做完了。","translation":"I finished my homework.","hsk":3,"grammar":"ba_disposal"},
    {"sentence":"请把这个字写在本子上。","translation":"Please write this character in the notebook.","hsk":3,"grammar":"ba_disposal"},
    {"sentence":"他越说越快。","translation":"The more he speaks, the faster he goes.","hsk":3,"grammar":"yue_yue"},
    {"sentence":"雨越下越大。","translation":"The rain falls heavier and heavier.","hsk":3,"grammar":"yue_yue"},
    {"sentence":"我已经把饭吃完了。","translation":"I have already finished the meal.","hsk":3,"grammar":"ba_disposal"},
    {"sentence":"他被妈妈叫回家了。","translation":"He was called home by his mother.","hsk":3,"grammar":"bei_passive"},
    {"sentence":"桌子上放着一本书。","translation":"There is a book on the table.","hsk":3,"grammar":"zhe_continuous"},
]

# Grammar points: rolled out one new point every 3 days.
# Between new points, earlier ones recur with fresh examples.
# All points seen in a week feed into the weekly test.
GRAMMAR_POINTS = [
    {"id":"shi_to_be","hsk":1,"title":"是 - the verb 'to be'",
     "rule":"是 (shi) links two nouns: A 是 B = 'A is B'. Never use 是 to connect a noun and an adjective - for that, use 很. Negate with 不: 不是.",
     "examples":["我是学生。 - I am a student.","他不是老师。 - He is not a teacher.","这是书。 - This is a book."]},
    {"id":"hen_adj","hsk":1,"title":"很 + adjective",
     "rule":"To say 'X is [adjective]', use Subject + 很 + adjective. NO 是. 很 often just links - it doesn't always mean 'very'. Example: 我很好 = I'm fine (not 'I'm very good').",
     "examples":["今天很热。 - Today is hot.","她很漂亮。 - She is pretty.","我们很忙。 - We are busy."]},
    {"id":"you_have","hsk":1,"title":"有 - to have / there is",
     "rule":"有 (you) = 'to have' or 'there is/are'. Negate ONLY with 没 (never 不): 没有. 'I don't have' = 我没有.",
     "examples":["我有一本书。 - I have a book.","桌子上有杯子。 - There's a cup on the table.","我没有钱。 - I have no money."]},
    {"id":"ma_question","hsk":1,"title":"吗 - yes/no questions",
     "rule":"Add 吗 (ma) to the end of a statement to make it a yes/no question. The word order does NOT change. 你好 -> 你好吗?",
     "examples":["你是学生吗？ - Are you a student?","他喝茶吗？ - Does he drink tea?","好吗？ - Is that okay?"]},
    {"id":"de_possessive","hsk":1,"title":"的 - possession & description",
     "rule":"的 (de) shows possession (我的书 = my book) or links a description to a noun (漂亮的花 = pretty flower). Pattern: [owner/adjective] + 的 + [noun].",
     "examples":["我的手机 - my phone","老师的书 - the teacher's book","红色的车 - a red car"]},
    {"id":"le_completed","hsk":2,"title":"了 - completed action",
     "rule":"了 (le) after a verb marks a completed/realized action. 我吃了 = I ate. It also marks a change of state at sentence end: 下雨了 = it started raining.",
     "examples":["我买了一本书。 - I bought a book.","他走了。 - He left.","天黑了。 - It got dark."]},
    {"id":"zai_progressive","hsk":2,"title":"在 + verb - ongoing action",
     "rule":"(正)在 + verb = an action in progress, like English '-ing'. 我在吃饭 = I am eating. Often paired with 呢 at the end.",
     "examples":["我在看书。 - I am reading.","他正在睡觉。 - He is sleeping.","你在做什么呢？ - What are you doing?"]},
    {"id":"bi_comparison","hsk":2,"title":"比 - comparisons",
     "rule":"A 比 B + adjective = 'A is more [adjective] than B'. Do NOT add 很. To say 'much more', add 得多 or 多了 after: A 比 B 高得多.",
     "examples":["我比你高。 - I'm taller than you.","今天比昨天热。 - Today is hotter than yesterday.","他比我大三岁。 - He's 3 years older than me."]},
    {"id":"yao_want","hsk":2,"title":"要 / 想 - want to",
     "rule":"想 (xiang) = would like to (softer). 要 (yao) = want to / will (stronger, more definite). 我想去 = I'd like to go; 我要去 = I want/intend to go.",
     "examples":["我想喝茶。 - I'd like tea.","我要回家。 - I want to go home.","你想吃什么？ - What would you like to eat?"]},
    {"id":"yinwei_suoyi","hsk":2,"title":"因为...所以... - because...therefore",
     "rule":"因为 (because) + reason, 所以 (so/therefore) + result. Both halves can appear together - this is normal in Chinese, unlike English where you'd drop one.",
     "examples":["因为下雨，所以我没去。 - Because it rained, I didn't go.","因为累，所以早睡了。 - Because tired, I slept early."]},
    {"id":"guo_experiential","hsk":2,"title":"过 - experiential aspect",
     "rule":"verb + 过 (guo) = 'have ever done' (a past experience). 我去过北京 = I have been to Beijing. Negate with 没: 没去过.",
     "examples":["我吃过中国菜。 - I've eaten Chinese food.","他没看过这部电影。 - He hasn't seen this movie.","你去过吗？ - Have you ever been?"]},
    {"id":"ruguo_if","hsk":2,"title":"如果...就... - if...then",
     "rule":"如果 (if) + condition, (subject) 就 (then) + result. 就 sits right before the verb in the result clause.",
     "examples":["如果下雨，我就不去。 - If it rains, I won't go.","如果你忙，就别来了。 - If you're busy, don't come."]},
    {"id":"ba_disposal","hsk":3,"title":"把 - the disposal construction",
     "rule":"把 (ba) moves the object BEFORE the verb to emphasize what happens to it. Pattern: Subject + 把 + object + verb + (complement/了). The verb must do something TO the object. 我把书放好了 = I put the book away.",
     "examples":["我把门关上了。 - I closed the door.","请把这个拿走。 - Please take this away.","他把饭吃完了。 - He finished the food."]},
    {"id":"bei_passive","hsk":3,"title":"被 - the passive",
     "rule":"被 (bei) makes a passive sentence: Object + 被 + (doer) + verb + (result). 我的钱被偷了 = My money was stolen. The doer can be omitted.",
     "examples":["杯子被打破了。 - The cup was broken.","他被老师表扬了。 - He was praised by the teacher.","书被借走了。 - The book was borrowed."]},
    {"id":"zhe_continuous","hsk":3,"title":"着 - continuous state",
     "rule":"verb + 着 (zhe) shows an ongoing STATE (not action). 门开着 = the door is (in the state of being) open. Often describes how something exists: 站着 = standing.",
     "examples":["门开着。 - The door is open.","他笑着说。 - He said with a smile.","墙上挂着画。 - A painting hangs on the wall."]},
    {"id":"de_complement","hsk":3,"title":"得 - complement of degree",
     "rule":"verb + 得 (de) + adjective describes HOW WELL an action is done. 他跑得很快 = he runs fast. With an object: 他说中文说得很好 (repeat the verb).",
     "examples":["她唱得很好。 - She sings well.","他来得很早。 - He came early.","你写得不错。 - You write quite well."]},
    {"id":"resultative_complement","hsk":3,"title":"Resultative complements (完, 懂, 好...)",
     "rule":"A second verb/adjective after the main verb shows the RESULT. 看完 = finish reading, 听懂 = understand (by hearing), 做好 = finish doing well. Negate with 没: 没看完.",
     "examples":["我吃完了。 - I finished eating.","他听懂了。 - He understood.","作业做好了。 - The homework is done."]},
    {"id":"weile_purpose","hsk":3,"title":"为了 - in order to",
     "rule":"为了 (weile) + goal, then the action. 为了健康，我每天跑步 = For my health, I run daily. States the purpose first.",
     "examples":["为了学中文，我去了中国。 - To learn Chinese, I went to China.","为了你，我什么都愿意。 - For you, I'd do anything."]},
    {"id":"budan_erqie","hsk":3,"title":"不但...而且... - not only...but also",
     "rule":"不但 (not only) + first point, 而且 (moreover) + second, stronger point. 还 or 也 can replace 而且.",
     "examples":["他不但聪明，而且努力。 - Not only smart but also hardworking.","这里不但便宜，而且好吃。 - Not only cheap but also tasty."]},
    {"id":"yuelaiyue","hsk":3,"title":"越来越 - more and more",
     "rule":"越来越 + adjective = 'more and more [adjective]' over time. 天气越来越热 = the weather is getting hotter and hotter.",
     "examples":["他越来越高了。 - He's getting taller.","我越来越喜欢中文。 - I like Chinese more and more."]},
    {"id":"yue_yue","hsk":3,"title":"越...越... - the more...the more",
     "rule":"越 + verb1 + 越 + verb2/adj = 'the more X, the more Y'. 越学越有意思 = the more you study, the more interesting it gets.",
     "examples":["越说越快。 - The more he talks the faster he gets.","雨越下越大。 - The more it rains the harder it falls."]},
    {"id":"yibian_yibian","hsk":3,"title":"一边...一边... - doing two things at once",
     "rule":"一边 + verb1 + 一边 + verb2 = doing two actions simultaneously. 我一边吃饭一边看电视 = I watch TV while eating.",
     "examples":["他一边走一边唱。 - He walks and sings.","别一边开车一边打电话。 - Don't phone while driving."]},
    {"id":"zhiyao_jiu","hsk":3,"title":"只要...就... - as long as",
     "rule":"只要 (as long as) + condition, 就 + result. 只要努力，就能成功 = as long as you work hard, you can succeed. Compare 只有...才 (only if).",
     "examples":["只要你来，我就高兴。 - As long as you come, I'm happy.","只要有钱就行。 - As long as there's money it's fine."]},
    {"id":"shi_de_emphasis","hsk":3,"title":"是...的 - emphasizing details",
     "rule":"For a completed action, 是...的 emphasizes WHEN/WHERE/HOW it happened. 我是昨天来的 = It was yesterday that I came. The 是 can be dropped, 的 cannot.",
     "examples":["我是坐飞机来的。 - I came by plane.","他是在北京出生的。 - He was born in Beijing."]},
    # function-word helpers reused by HSK1 sentences
    {"id":"svo_basic","hsk":1,"title":"Basic word order: S-V-O",
     "rule":"Chinese basic order is Subject-Verb-Object, same as English. 我(S) 喝(V) 茶(O) = I drink tea. Time and place words go BEFORE the verb, not after.",
     "examples":["我喝茶。 - I drink tea.","他看书。 - He reads books.","我们去学校。 - We go to school."]},
    {"id":"question_what","hsk":1,"title":"Question words stay in place",
     "rule":"In Chinese, question words (什么 what, 谁 who, 哪儿 where) sit where the answer would go - the sentence order does NOT change. 你吃什么? = You eat what?",
     "examples":["你叫什么名字？ - What's your name?","他是谁？ - Who is he?","你去哪儿？ - Where are you going?"]},
    {"id":"bu_negation","hsk":1,"title":"不 - general negation",
     "rule":"不 (bu) negates verbs and adjectives (present/future/habit). 我不去 = I'm not going. The ONE exception: 有 is negated by 没, never 不.",
     "examples":["我不喝酒。 - I don't drink alcohol.","他不高。 - He's not tall.","今天不冷。 - It's not cold today."]},
    {"id":"gei_give","hsk":2,"title":"给 - to give / for",
     "rule":"给 (gei) = give. Pattern: give + person + thing: 给我一本书. Also marks the recipient before a verb: 给你打电话 = call you.",
     "examples":["请给我水。 - Please give me water.","我给你做饭。 - I'll cook for you."]},
    {"id":"xiang_want","hsk":2,"title":"想 - would like / to miss",
     "rule":"想 (xiang) + verb = would like to do (soft wish). 想 + noun/person = to miss. 我想你 = I miss you. 我想去 = I'd like to go.",
     "examples":["我想休息。 - I'd like to rest.","我很想家。 - I miss home a lot."]},
    {"id":"cong_from","hsk":2,"title":"从 - from (origin/start point)",
     "rule":"从 (cong) marks a starting point in space or time. 从北京来 = come from Beijing. 从...到... = from...to...",
     "examples":["我从中国来。 - I come from China.","从九点到五点。 - From 9 to 5."]},
    {"id":"suiran_danshi","hsk":2,"title":"虽然...但是... - although",
     "rule":"虽然 (although) + fact, 但是 (but) + contrasting point. BOTH halves appear together in Chinese - don't drop 但是 the way English drops 'but'.",
     "examples":["虽然累，但是很开心。 - Although tired, very happy.","虽然贵，但是好。 - Although expensive, it's good."]},
]
