"""
HSK 1-6 Vocabulary
Full list: ~5,000 words across 6 levels.
Each entry: id, hsk level, char, pinyin, meaning_en, meaning_ru, alt_en (optional)
"""

HSK_WORDS = [
    # ── HSK 1 (150 words) ──────────────────────────────────────────────────
    {"id":"1_001","hsk":1,"char":"爱","pinyin":"ài","meaning_en":"to love","meaning_ru":"любить"},
    {"id":"1_002","hsk":1,"char":"八","pinyin":"bā","meaning_en":"eight","meaning_ru":"восемь"},
    {"id":"1_003","hsk":1,"char":"爸爸","pinyin":"bàba","meaning_en":"father","meaning_ru":"папа","alt_en":["dad"]},
    {"id":"1_004","hsk":1,"char":"杯子","pinyin":"bēizi","meaning_en":"cup","meaning_ru":"чашка","alt_en":["glass"]},
    {"id":"1_005","hsk":1,"char":"北京","pinyin":"Běijīng","meaning_en":"Beijing","meaning_ru":"Пекин"},
    {"id":"1_006","hsk":1,"char":"本","pinyin":"běn","meaning_en":"(measure word for books)","meaning_ru":"(счётное слово для книг)"},
    {"id":"1_007","hsk":1,"char":"不客气","pinyin":"bù kèqi","meaning_en":"you're welcome","meaning_ru":"пожалуйста","alt_en":["don't mention it"]},
    {"id":"1_008","hsk":1,"char":"不","pinyin":"bù","meaning_en":"not; no","meaning_ru":"не; нет"},
    {"id":"1_009","hsk":1,"char":"菜","pinyin":"cài","meaning_en":"dish; vegetable","meaning_ru":"блюдо; овощ"},
    {"id":"1_010","hsk":1,"char":"茶","pinyin":"chá","meaning_en":"tea","meaning_ru":"чай"},
    {"id":"1_011","hsk":1,"char":"吃","pinyin":"chī","meaning_en":"to eat","meaning_ru":"есть; кушать"},
    {"id":"1_012","hsk":1,"char":"出租车","pinyin":"chūzūchē","meaning_en":"taxi","meaning_ru":"такси"},
    {"id":"1_013","hsk":1,"char":"打电话","pinyin":"dǎ diànhuà","meaning_en":"to make a phone call","meaning_ru":"звонить по телефону"},
    {"id":"1_014","hsk":1,"char":"大","pinyin":"dà","meaning_en":"big; large","meaning_ru":"большой"},
    {"id":"1_015","hsk":1,"char":"的","pinyin":"de","meaning_en":"(possessive particle)","meaning_ru":"(частица принадлежности)"},
    {"id":"1_016","hsk":1,"char":"点","pinyin":"diǎn","meaning_en":"o'clock; a little","meaning_ru":"час; немного"},
    {"id":"1_017","hsk":1,"char":"电脑","pinyin":"diànnǎo","meaning_en":"computer","meaning_ru":"компьютер"},
    {"id":"1_018","hsk":1,"char":"电视","pinyin":"diànshì","meaning_en":"television","meaning_ru":"телевизор"},
    {"id":"1_019","hsk":1,"char":"电影","pinyin":"diànyǐng","meaning_en":"movie","meaning_ru":"фильм","alt_en":["film"]},
    {"id":"1_020","hsk":1,"char":"东西","pinyin":"dōngxi","meaning_en":"thing; stuff","meaning_ru":"вещь; штука"},
    {"id":"1_021","hsk":1,"char":"都","pinyin":"dōu","meaning_en":"both; all","meaning_ru":"оба; все"},
    {"id":"1_022","hsk":1,"char":"读","pinyin":"dú","meaning_en":"to read","meaning_ru":"читать"},
    {"id":"1_023","hsk":1,"char":"对不起","pinyin":"duìbuqǐ","meaning_en":"sorry","meaning_ru":"извините","alt_en":["excuse me"]},
    {"id":"1_024","hsk":1,"char":"多","pinyin":"duō","meaning_en":"many; much","meaning_ru":"много"},
    {"id":"1_025","hsk":1,"char":"多少","pinyin":"duōshao","meaning_en":"how many; how much","meaning_ru":"сколько"},
    {"id":"1_026","hsk":1,"char":"儿子","pinyin":"érzi","meaning_en":"son","meaning_ru":"сын"},
    {"id":"1_027","hsk":1,"char":"二","pinyin":"èr","meaning_en":"two","meaning_ru":"два"},
    {"id":"1_028","hsk":1,"char":"饭店","pinyin":"fàndiàn","meaning_en":"restaurant; hotel","meaning_ru":"ресторан; гостиница"},
    {"id":"1_029","hsk":1,"char":"飞机","pinyin":"fēijī","meaning_en":"airplane","meaning_ru":"самолёт"},
    {"id":"1_030","hsk":1,"char":"分钟","pinyin":"fēnzhōng","meaning_en":"minute","meaning_ru":"минута"},
    {"id":"1_031","hsk":1,"char":"高兴","pinyin":"gāoxìng","meaning_en":"happy; glad","meaning_ru":"счастливый; рад"},
    {"id":"1_032","hsk":1,"char":"个","pinyin":"gè","meaning_en":"(general measure word)","meaning_ru":"(общее счётное слово)"},
    {"id":"1_033","hsk":1,"char":"工作","pinyin":"gōngzuò","meaning_en":"work; job","meaning_ru":"работа"},
    {"id":"1_034","hsk":1,"char":"狗","pinyin":"gǒu","meaning_en":"dog","meaning_ru":"собака"},
    {"id":"1_035","hsk":1,"char":"汉语","pinyin":"Hànyǔ","meaning_en":"Chinese (language)","meaning_ru":"китайский язык"},
    {"id":"1_036","hsk":1,"char":"好","pinyin":"hǎo","meaning_en":"good; well","meaning_ru":"хорошо; хороший"},
    {"id":"1_037","hsk":1,"char":"号","pinyin":"hào","meaning_en":"number; date","meaning_ru":"номер; число"},
    {"id":"1_038","hsk":1,"char":"喝","pinyin":"hē","meaning_en":"to drink","meaning_ru":"пить"},
    {"id":"1_039","hsk":1,"char":"和","pinyin":"hé","meaning_en":"and; with","meaning_ru":"и; с"},
    {"id":"1_040","hsk":1,"char":"很","pinyin":"hěn","meaning_en":"very","meaning_ru":"очень"},
    {"id":"1_041","hsk":1,"char":"后面","pinyin":"hòumiàn","meaning_en":"behind; back","meaning_ru":"сзади; за"},
    {"id":"1_042","hsk":1,"char":"回","pinyin":"huí","meaning_en":"to return","meaning_ru":"возвращаться"},
    {"id":"1_043","hsk":1,"char":"会","pinyin":"huì","meaning_en":"can; will","meaning_ru":"уметь; будет"},
    {"id":"1_044","hsk":1,"char":"几","pinyin":"jǐ","meaning_en":"how many; several","meaning_ru":"сколько; несколько"},
    {"id":"1_045","hsk":1,"char":"家","pinyin":"jiā","meaning_en":"home; family","meaning_ru":"дом; семья"},
    {"id":"1_046","hsk":1,"char":"叫","pinyin":"jiào","meaning_en":"to be called; to call","meaning_ru":"называться; называть"},
    {"id":"1_047","hsk":1,"char":"今天","pinyin":"jīntiān","meaning_en":"today","meaning_ru":"сегодня"},
    {"id":"1_048","hsk":1,"char":"九","pinyin":"jiǔ","meaning_en":"nine","meaning_ru":"девять"},
    {"id":"1_049","hsk":1,"char":"开","pinyin":"kāi","meaning_en":"to open; to drive","meaning_ru":"открывать; ехать"},
    {"id":"1_050","hsk":1,"char":"看","pinyin":"kàn","meaning_en":"to look; to watch","meaning_ru":"смотреть; видеть"},
    {"id":"1_051","hsk":1,"char":"看见","pinyin":"kànjiàn","meaning_en":"to see","meaning_ru":"увидеть"},
    {"id":"1_052","hsk":1,"char":"块","pinyin":"kuài","meaning_en":"yuan (money); piece","meaning_ru":"юань; кусок"},
    {"id":"1_053","hsk":1,"char":"来","pinyin":"lái","meaning_en":"to come","meaning_ru":"приходить; приезжать"},
    {"id":"1_054","hsk":1,"char":"老师","pinyin":"lǎoshī","meaning_en":"teacher","meaning_ru":"учитель"},
    {"id":"1_055","hsk":1,"char":"了","pinyin":"le","meaning_en":"(completed action particle)","meaning_ru":"(частица завершённого действия)"},
    {"id":"1_056","hsk":1,"char":"冷","pinyin":"lěng","meaning_en":"cold","meaning_ru":"холодный"},
    {"id":"1_057","hsk":1,"char":"里","pinyin":"lǐ","meaning_en":"inside; in","meaning_ru":"внутри; в"},
    {"id":"1_058","hsk":1,"char":"六","pinyin":"liù","meaning_en":"six","meaning_ru":"шесть"},
    {"id":"1_059","hsk":1,"char":"妈妈","pinyin":"māma","meaning_en":"mother; mom","meaning_ru":"мама"},
    {"id":"1_060","hsk":1,"char":"吗","pinyin":"ma","meaning_en":"(question particle)","meaning_ru":"(вопросительная частица)"},
    {"id":"1_061","hsk":1,"char":"买","pinyin":"mǎi","meaning_en":"to buy","meaning_ru":"покупать"},
    {"id":"1_062","hsk":1,"char":"猫","pinyin":"māo","meaning_en":"cat","meaning_ru":"кошка"},
    {"id":"1_063","hsk":1,"char":"没关系","pinyin":"méi guānxi","meaning_en":"it's okay; never mind","meaning_ru":"ничего; не важно"},
    {"id":"1_064","hsk":1,"char":"没有","pinyin":"méiyǒu","meaning_en":"don't have; there isn't","meaning_ru":"нет; не иметь"},
    {"id":"1_065","hsk":1,"char":"米饭","pinyin":"mǐfàn","meaning_en":"cooked rice","meaning_ru":"варёный рис"},
    {"id":"1_066","hsk":1,"char":"明天","pinyin":"míngtiān","meaning_en":"tomorrow","meaning_ru":"завтра"},
    {"id":"1_067","hsk":1,"char":"名字","pinyin":"míngzi","meaning_en":"name","meaning_ru":"имя"},
    {"id":"1_068","hsk":1,"char":"哪","pinyin":"nǎ","meaning_en":"which","meaning_ru":"который; какой"},
    {"id":"1_069","hsk":1,"char":"那","pinyin":"nà","meaning_en":"that","meaning_ru":"тот; та; то"},
    {"id":"1_070","hsk":1,"char":"呢","pinyin":"ne","meaning_en":"(question particle)","meaning_ru":"(вопросительная частица)"},
    {"id":"1_071","hsk":1,"char":"能","pinyin":"néng","meaning_en":"can; to be able to","meaning_ru":"мочь; быть в состоянии"},
    {"id":"1_072","hsk":1,"char":"你","pinyin":"nǐ","meaning_en":"you","meaning_ru":"ты"},
    {"id":"1_073","hsk":1,"char":"年","pinyin":"nián","meaning_en":"year","meaning_ru":"год"},
    {"id":"1_074","hsk":1,"char":"女儿","pinyin":"nǚér","meaning_en":"daughter","meaning_ru":"дочь"},
    {"id":"1_075","hsk":1,"char":"朋友","pinyin":"péngyou","meaning_en":"friend","meaning_ru":"друг"},
    {"id":"1_076","hsk":1,"char":"漂亮","pinyin":"piàoliang","meaning_en":"beautiful; pretty","meaning_ru":"красивый"},
    {"id":"1_077","hsk":1,"char":"苹果","pinyin":"píngguǒ","meaning_en":"apple","meaning_ru":"яблоко"},
    {"id":"1_078","hsk":1,"char":"七","pinyin":"qī","meaning_en":"seven","meaning_ru":"семь"},
    {"id":"1_079","hsk":1,"char":"钱","pinyin":"qián","meaning_en":"money","meaning_ru":"деньги"},
    {"id":"1_080","hsk":1,"char":"请","pinyin":"qǐng","meaning_en":"please; to invite","meaning_ru":"пожалуйста; приглашать"},
    {"id":"1_081","hsk":1,"char":"去","pinyin":"qù","meaning_en":"to go","meaning_ru":"идти; ехать"},
    {"id":"1_082","hsk":1,"char":"热","pinyin":"rè","meaning_en":"hot","meaning_ru":"горячий; жаркий"},
    {"id":"1_083","hsk":1,"char":"人","pinyin":"rén","meaning_en":"person; people","meaning_ru":"человек; люди"},
    {"id":"1_084","hsk":1,"char":"认识","pinyin":"rènshi","meaning_en":"to know; to recognize","meaning_ru":"знать; узнавать"},
    {"id":"1_085","hsk":1,"char":"日","pinyin":"rì","meaning_en":"day; sun","meaning_ru":"день; солнце"},
    {"id":"1_086","hsk":1,"char":"三","pinyin":"sān","meaning_en":"three","meaning_ru":"три"},
    {"id":"1_087","hsk":1,"char":"商店","pinyin":"shāngdiàn","meaning_en":"shop; store","meaning_ru":"магазин"},
    {"id":"1_088","hsk":1,"char":"上","pinyin":"shàng","meaning_en":"on; above; to go up","meaning_ru":"на; выше; подниматься"},
    {"id":"1_089","hsk":1,"char":"上午","pinyin":"shàngwǔ","meaning_en":"morning; a.m.","meaning_ru":"утро; до полудня"},
    {"id":"1_090","hsk":1,"char":"少","pinyin":"shǎo","meaning_en":"few; little","meaning_ru":"мало; немного"},
    {"id":"1_091","hsk":1,"char":"谁","pinyin":"shéi","meaning_en":"who","meaning_ru":"кто"},
    {"id":"1_092","hsk":1,"char":"什么","pinyin":"shénme","meaning_en":"what","meaning_ru":"что; какой"},
    {"id":"1_093","hsk":1,"char":"十","pinyin":"shí","meaning_en":"ten","meaning_ru":"десять"},
    {"id":"1_094","hsk":1,"char":"时候","pinyin":"shíhou","meaning_en":"time; moment","meaning_ru":"время; момент"},
    {"id":"1_095","hsk":1,"char":"是","pinyin":"shì","meaning_en":"to be; is","meaning_ru":"быть; является"},
    {"id":"1_096","hsk":1,"char":"书","pinyin":"shū","meaning_en":"book","meaning_ru":"книга"},
    {"id":"1_097","hsk":1,"char":"水","pinyin":"shuǐ","meaning_en":"water","meaning_ru":"вода"},
    {"id":"1_098","hsk":1,"char":"水果","pinyin":"shuǐguǒ","meaning_en":"fruit","meaning_ru":"фрукт"},
    {"id":"1_099","hsk":1,"char":"睡觉","pinyin":"shuìjiào","meaning_en":"to sleep","meaning_ru":"спать"},
    {"id":"1_100","hsk":1,"char":"说","pinyin":"shuō","meaning_en":"to speak; to say","meaning_ru":"говорить; сказать"},
    {"id":"1_101","hsk":1,"char":"四","pinyin":"sì","meaning_en":"four","meaning_ru":"четыре"},
    {"id":"1_102","hsk":1,"char":"岁","pinyin":"suì","meaning_en":"year (of age)","meaning_ru":"год (возраст)"},
    {"id":"1_103","hsk":1,"char":"他","pinyin":"tā","meaning_en":"he; him","meaning_ru":"он"},
    {"id":"1_104","hsk":1,"char":"她","pinyin":"tā","meaning_en":"she; her","meaning_ru":"она"},
    {"id":"1_105","hsk":1,"char":"太","pinyin":"tài","meaning_en":"too; extremely","meaning_ru":"слишком; очень"},
    {"id":"1_106","hsk":1,"char":"天气","pinyin":"tiānqì","meaning_en":"weather","meaning_ru":"погода"},
    {"id":"1_107","hsk":1,"char":"听","pinyin":"tīng","meaning_en":"to listen","meaning_ru":"слушать"},
    {"id":"1_108","hsk":1,"char":"同学","pinyin":"tóngxué","meaning_en":"classmate","meaning_ru":"одноклассник"},
    {"id":"1_109","hsk":1,"char":"喂","pinyin":"wèi","meaning_en":"hello (on phone)","meaning_ru":"алло"},
    {"id":"1_110","hsk":1,"char":"我","pinyin":"wǒ","meaning_en":"I; me","meaning_ru":"я; меня"},
    {"id":"1_111","hsk":1,"char":"我们","pinyin":"wǒmen","meaning_en":"we; us","meaning_ru":"мы"},
    {"id":"1_112","hsk":1,"char":"五","pinyin":"wǔ","meaning_en":"five","meaning_ru":"пять"},
    {"id":"1_113","hsk":1,"char":"下午","pinyin":"xiàwǔ","meaning_en":"afternoon; p.m.","meaning_ru":"после полудня; вечер"},
    {"id":"1_114","hsk":1,"char":"下雨","pinyin":"xià yǔ","meaning_en":"to rain","meaning_ru":"идти дождю"},
    {"id":"1_115","hsk":1,"char":"先生","pinyin":"xiānsheng","meaning_en":"Mr.; husband","meaning_ru":"господин; муж"},
    {"id":"1_116","hsk":1,"char":"现在","pinyin":"xiànzài","meaning_en":"now; currently","meaning_ru":"сейчас; в настоящее время"},
    {"id":"1_117","hsk":1,"char":"想","pinyin":"xiǎng","meaning_en":"to want; to think","meaning_ru":"хотеть; думать"},
    {"id":"1_118","hsk":1,"char":"小","pinyin":"xiǎo","meaning_en":"small; little","meaning_ru":"маленький"},
    {"id":"1_119","hsk":1,"char":"小姐","pinyin":"xiǎojiě","meaning_en":"Miss; young lady","meaning_ru":"мисс; девушка"},
    {"id":"1_120","hsk":1,"char":"些","pinyin":"xiē","meaning_en":"some; a few","meaning_ru":"несколько; немного"},
    {"id":"1_121","hsk":1,"char":"写","pinyin":"xiě","meaning_en":"to write","meaning_ru":"писать"},
    {"id":"1_122","hsk":1,"char":"谢谢","pinyin":"xièxie","meaning_en":"thank you","meaning_ru":"спасибо"},
    {"id":"1_123","hsk":1,"char":"星期","pinyin":"xīngqī","meaning_en":"week","meaning_ru":"неделя"},
    {"id":"1_124","hsk":1,"char":"学生","pinyin":"xuésheng","meaning_en":"student","meaning_ru":"студент; ученик"},
    {"id":"1_125","hsk":1,"char":"学习","pinyin":"xuéxí","meaning_en":"to study; to learn","meaning_ru":"учиться; изучать"},
    {"id":"1_126","hsk":1,"char":"学校","pinyin":"xuéxiào","meaning_en":"school","meaning_ru":"школа"},
    {"id":"1_127","hsk":1,"char":"一","pinyin":"yī","meaning_en":"one","meaning_ru":"один"},
    {"id":"1_128","hsk":1,"char":"一些","pinyin":"yīxiē","meaning_en":"some; a few","meaning_ru":"некоторые; немного"},
    {"id":"1_129","hsk":1,"char":"医生","pinyin":"yīshēng","meaning_en":"doctor","meaning_ru":"врач; доктор"},
    {"id":"1_130","hsk":1,"char":"医院","pinyin":"yīyuàn","meaning_en":"hospital","meaning_ru":"больница"},
    {"id":"1_131","hsk":1,"char":"椅子","pinyin":"yǐzi","meaning_en":"chair","meaning_ru":"стул"},
    {"id":"1_132","hsk":1,"char":"有","pinyin":"yǒu","meaning_en":"to have; there is","meaning_ru":"иметь; есть"},
    {"id":"1_133","hsk":1,"char":"月","pinyin":"yuè","meaning_en":"month; moon","meaning_ru":"месяц; луна"},
    {"id":"1_134","hsk":1,"char":"在","pinyin":"zài","meaning_en":"at; in; to be at","meaning_ru":"в; находиться"},
    {"id":"1_135","hsk":1,"char":"再见","pinyin":"zàijiàn","meaning_en":"goodbye","meaning_ru":"до свидания"},
    {"id":"1_136","hsk":1,"char":"怎么","pinyin":"zěnme","meaning_en":"how; why","meaning_ru":"как; почему"},
    {"id":"1_137","hsk":1,"char":"怎么样","pinyin":"zěnmeyàng","meaning_en":"how about; how is it","meaning_ru":"как; что скажешь"},
    {"id":"1_138","hsk":1,"char":"这","pinyin":"zhè","meaning_en":"this","meaning_ru":"этот; эта; это"},
    {"id":"1_139","hsk":1,"char":"中国","pinyin":"Zhōngguó","meaning_en":"China","meaning_ru":"Китай"},
    {"id":"1_140","hsk":1,"char":"中午","pinyin":"zhōngwǔ","meaning_en":"noon; midday","meaning_ru":"полдень"},
    {"id":"1_141","hsk":1,"char":"住","pinyin":"zhù","meaning_en":"to live; to stay","meaning_ru":"жить; проживать"},
    {"id":"1_142","hsk":1,"char":"桌子","pinyin":"zhuōzi","meaning_en":"table; desk","meaning_ru":"стол"},
    {"id":"1_143","hsk":1,"char":"字","pinyin":"zì","meaning_en":"character; word","meaning_ru":"иероглиф; слово"},
    {"id":"1_144","hsk":1,"char":"昨天","pinyin":"zuótiān","meaning_en":"yesterday","meaning_ru":"вчера"},
    {"id":"1_145","hsk":1,"char":"坐","pinyin":"zuò","meaning_en":"to sit; to travel by","meaning_ru":"сидеть; ехать на"},
    {"id":"1_146","hsk":1,"char":"做","pinyin":"zuò","meaning_en":"to do; to make","meaning_ru":"делать"},
    {"id":"1_147","hsk":1,"char":"零","pinyin":"líng","meaning_en":"zero","meaning_ru":"ноль"},
    {"id":"1_148","hsk":1,"char":"百","pinyin":"bǎi","meaning_en":"hundred","meaning_ru":"сто"},
    {"id":"1_149","hsk":1,"char":"千","pinyin":"qiān","meaning_en":"thousand","meaning_ru":"тысяча"},
    {"id":"1_150","hsk":1,"char":"万","pinyin":"wàn","meaning_en":"ten thousand","meaning_ru":"десять тысяч"},

    # ── HSK 2 (150 words) ──────────────────────────────────────────────────
    {"id":"2_001","hsk":2,"char":"吧","pinyin":"ba","meaning_en":"(suggestion particle)","meaning_ru":"(частица предположения)"},
    {"id":"2_002","hsk":2,"char":"白","pinyin":"bái","meaning_en":"white","meaning_ru":"белый"},
    {"id":"2_003","hsk":2,"char":"百","pinyin":"bǎi","meaning_en":"hundred","meaning_ru":"сто"},
    {"id":"2_004","hsk":2,"char":"帮助","pinyin":"bāngzhù","meaning_en":"to help","meaning_ru":"помогать"},
    {"id":"2_005","hsk":2,"char":"报纸","pinyin":"bàozhǐ","meaning_en":"newspaper","meaning_ru":"газета"},
    {"id":"2_006","hsk":2,"char":"比","pinyin":"bǐ","meaning_en":"to compare; than","meaning_ru":"сравнивать; чем"},
    {"id":"2_007","hsk":2,"char":"别","pinyin":"bié","meaning_en":"don't; other","meaning_ru":"не; другой"},
    {"id":"2_008","hsk":2,"char":"宾馆","pinyin":"bīnguǎn","meaning_en":"hotel","meaning_ru":"гостиница"},
    {"id":"2_009","hsk":2,"char":"长","pinyin":"cháng","meaning_en":"long","meaning_ru":"длинный"},
    {"id":"2_010","hsk":2,"char":"唱歌","pinyin":"chànggē","meaning_en":"to sing","meaning_ru":"петь"},
    {"id":"2_011","hsk":2,"char":"出","pinyin":"chū","meaning_en":"to exit; to go out","meaning_ru":"выходить"},
    {"id":"2_012","hsk":2,"char":"穿","pinyin":"chuān","meaning_en":"to wear; to put on","meaning_ru":"носить; надевать"},
    {"id":"2_013","hsk":2,"char":"次","pinyin":"cì","meaning_en":"time; occurrence","meaning_ru":"раз; случай"},
    {"id":"2_014","hsk":2,"char":"从","pinyin":"cóng","meaning_en":"from","meaning_ru":"от; из"},
    {"id":"2_015","hsk":2,"char":"错","pinyin":"cuò","meaning_en":"wrong; mistake","meaning_ru":"неправильно; ошибка"},
    {"id":"2_016","hsk":2,"char":"打篮球","pinyin":"dǎ lánqiú","meaning_en":"to play basketball","meaning_ru":"играть в баскетбол"},
    {"id":"2_017","hsk":2,"char":"大家","pinyin":"dàjiā","meaning_en":"everyone","meaning_ru":"все; каждый"},
    {"id":"2_018","hsk":2,"char":"到","pinyin":"dào","meaning_en":"to arrive; to","meaning_ru":"прибывать; до"},
    {"id":"2_019","hsk":2,"char":"地方","pinyin":"dìfang","meaning_en":"place","meaning_ru":"место"},
    {"id":"2_020","hsk":2,"char":"弟弟","pinyin":"dìdi","meaning_en":"younger brother","meaning_ru":"младший брат"},
    {"id":"2_021","hsk":2,"char":"第一","pinyin":"dì yī","meaning_en":"first","meaning_ru":"первый"},
    {"id":"2_022","hsk":2,"char":"懂","pinyin":"dǒng","meaning_en":"to understand","meaning_ru":"понимать"},
    {"id":"2_023","hsk":2,"char":"对","pinyin":"duì","meaning_en":"correct; right","meaning_ru":"правильно; верно"},
    {"id":"2_024","hsk":2,"char":"房间","pinyin":"fángjiān","meaning_en":"room","meaning_ru":"комната"},
    {"id":"2_025","hsk":2,"char":"非常","pinyin":"fēicháng","meaning_en":"very; extremely","meaning_ru":"очень; чрезвычайно"},
    {"id":"2_026","hsk":2,"char":"服务员","pinyin":"fúwùyuán","meaning_en":"waiter; attendant","meaning_ru":"официант; служащий"},
    {"id":"2_027","hsk":2,"char":"高","pinyin":"gāo","meaning_en":"tall; high","meaning_ru":"высокий"},
    {"id":"2_028","hsk":2,"char":"告诉","pinyin":"gàosu","meaning_en":"to tell","meaning_ru":"говорить; сообщать"},
    {"id":"2_029","hsk":2,"char":"哥哥","pinyin":"gēge","meaning_en":"older brother","meaning_ru":"старший брат"},
    {"id":"2_030","hsk":2,"char":"给","pinyin":"gěi","meaning_en":"to give; for","meaning_ru":"давать; для"},
    {"id":"2_031","hsk":2,"char":"公共汽车","pinyin":"gōnggòng qìchē","meaning_en":"bus","meaning_ru":"автобус"},
    {"id":"2_032","hsk":2,"char":"公司","pinyin":"gōngsī","meaning_en":"company","meaning_ru":"компания; фирма"},
    {"id":"2_033","hsk":2,"char":"贵","pinyin":"guì","meaning_en":"expensive","meaning_ru":"дорогой"},
    {"id":"2_034","hsk":2,"char":"过","pinyin":"guò","meaning_en":"to pass; (experiential)","meaning_ru":"проходить; (опытный аспект)"},
    {"id":"2_035","hsk":2,"char":"还","pinyin":"hái","meaning_en":"still; also","meaning_ru":"ещё; также"},
    {"id":"2_036","hsk":2,"char":"黑","pinyin":"hēi","meaning_en":"black","meaning_ru":"чёрный"},
    {"id":"2_037","hsk":2,"char":"红","pinyin":"hóng","meaning_en":"red","meaning_ru":"красный"},
    {"id":"2_038","hsk":2,"char":"欢迎","pinyin":"huānyíng","meaning_en":"welcome","meaning_ru":"добро пожаловать"},
    {"id":"2_039","hsk":2,"char":"还是","pinyin":"háishi","meaning_en":"or; still","meaning_ru":"или; всё ещё"},
    {"id":"2_040","hsk":2,"char":"火车站","pinyin":"huǒchēzhàn","meaning_en":"train station","meaning_ru":"железнодорожная станция"},
    {"id":"2_041","hsk":2,"char":"机场","pinyin":"jīchǎng","meaning_en":"airport","meaning_ru":"аэропорт"},
    {"id":"2_042","hsk":2,"char":"鸡蛋","pinyin":"jīdàn","meaning_en":"egg","meaning_ru":"яйцо"},
    {"id":"2_043","hsk":2,"char":"件","pinyin":"jiàn","meaning_en":"(measure for clothing/matters)","meaning_ru":"(счётное для одежды/дел)"},
    {"id":"2_044","hsk":2,"char":"教室","pinyin":"jiàoshì","meaning_en":"classroom","meaning_ru":"аудитория; класс"},
    {"id":"2_045","hsk":2,"char":"姐姐","pinyin":"jiějie","meaning_en":"older sister","meaning_ru":"старшая сестра"},
    {"id":"2_046","hsk":2,"char":"介绍","pinyin":"jièshào","meaning_en":"to introduce","meaning_ru":"представлять; знакомить"},
    {"id":"2_047","hsk":2,"char":"进","pinyin":"jìn","meaning_en":"to enter","meaning_ru":"входить"},
    {"id":"2_048","hsk":2,"char":"近","pinyin":"jìn","meaning_en":"near; close","meaning_ru":"близко; рядом"},
    {"id":"2_049","hsk":2,"char":"就","pinyin":"jiù","meaning_en":"then; exactly","meaning_ru":"тогда; именно"},
    {"id":"2_050","hsk":2,"char":"觉得","pinyin":"juéde","meaning_en":"to feel; to think","meaning_ru":"чувствовать; думать"},
    {"id":"2_051","hsk":2,"char":"咖啡","pinyin":"kāfēi","meaning_en":"coffee","meaning_ru":"кофе"},
    {"id":"2_052","hsk":2,"char":"开始","pinyin":"kāishǐ","meaning_en":"to start; beginning","meaning_ru":"начинать; начало"},
    {"id":"2_053","hsk":2,"char":"考试","pinyin":"kǎoshì","meaning_en":"exam; to take an exam","meaning_ru":"экзамен; сдавать экзамен"},
    {"id":"2_054","hsk":2,"char":"可以","pinyin":"kěyǐ","meaning_en":"can; may","meaning_ru":"можно; мочь"},
    {"id":"2_055","hsk":2,"char":"课","pinyin":"kè","meaning_en":"class; lesson","meaning_ru":"урок; занятие"},
    {"id":"2_056","hsk":2,"char":"快","pinyin":"kuài","meaning_en":"fast; quick","meaning_ru":"быстро; скорый"},
    {"id":"2_057","hsk":2,"char":"快乐","pinyin":"kuàilè","meaning_en":"happy; joyful","meaning_ru":"счастливый; радостный"},
    {"id":"2_058","hsk":2,"char":"累","pinyin":"lèi","meaning_en":"tired","meaning_ru":"уставший"},
    {"id":"2_059","hsk":2,"char":"离","pinyin":"lí","meaning_en":"away from; from","meaning_ru":"от; вдали от"},
    {"id":"2_060","hsk":2,"char":"练习","pinyin":"liànxí","meaning_en":"to practice","meaning_ru":"практиковаться; упражняться"},
    {"id":"2_061","hsk":2,"char":"两","pinyin":"liǎng","meaning_en":"two (of something)","meaning_ru":"два (с существительным)"},
    {"id":"2_062","hsk":2,"char":"零","pinyin":"líng","meaning_en":"zero","meaning_ru":"ноль"},
    {"id":"2_063","hsk":2,"char":"路","pinyin":"lù","meaning_en":"road; route","meaning_ru":"дорога; маршрут"},
    {"id":"2_064","hsk":2,"char":"旅游","pinyin":"lǚyóu","meaning_en":"to travel; tourism","meaning_ru":"путешествовать; туризм"},
    {"id":"2_065","hsk":2,"char":"卖","pinyin":"mài","meaning_en":"to sell","meaning_ru":"продавать"},
    {"id":"2_066","hsk":2,"char":"慢","pinyin":"màn","meaning_en":"slow","meaning_ru":"медленный"},
    {"id":"2_067","hsk":2,"char":"忙","pinyin":"máng","meaning_en":"busy","meaning_ru":"занятый"},
    {"id":"2_068","hsk":2,"char":"每","pinyin":"měi","meaning_en":"every; each","meaning_ru":"каждый"},
    {"id":"2_069","hsk":2,"char":"妹妹","pinyin":"mèimei","meaning_en":"younger sister","meaning_ru":"младшая сестра"},
    {"id":"2_070","hsk":2,"char":"门","pinyin":"mén","meaning_en":"door; gate","meaning_ru":"дверь; ворота"},
    {"id":"2_071","hsk":2,"char":"面条","pinyin":"miàntiáo","meaning_en":"noodles","meaning_ru":"лапша"},
    {"id":"2_072","hsk":2,"char":"男","pinyin":"nán","meaning_en":"male; man","meaning_ru":"мужской; мужчина"},
    {"id":"2_073","hsk":2,"char":"您","pinyin":"nín","meaning_en":"you (polite)","meaning_ru":"Вы (вежливое)"},
    {"id":"2_074","hsk":2,"char":"牛奶","pinyin":"niúnǎi","meaning_en":"milk","meaning_ru":"молоко"},
    {"id":"2_075","hsk":2,"char":"女","pinyin":"nǚ","meaning_en":"female; woman","meaning_ru":"женский; женщина"},
    {"id":"2_076","hsk":2,"char":"旁边","pinyin":"pángbiān","meaning_en":"beside; next to","meaning_ru":"рядом; сбоку"},
    {"id":"2_077","hsk":2,"char":"跑步","pinyin":"pǎobù","meaning_en":"to run","meaning_ru":"бегать"},
    {"id":"2_078","hsk":2,"char":"便宜","pinyin":"piányi","meaning_en":"cheap; inexpensive","meaning_ru":"дёшево; дешёвый"},
    {"id":"2_079","hsk":2,"char":"票","pinyin":"piào","meaning_en":"ticket","meaning_ru":"билет"},
    {"id":"2_080","hsk":2,"char":"妻子","pinyin":"qīzi","meaning_en":"wife","meaning_ru":"жена"},
    {"id":"2_081","hsk":2,"char":"起床","pinyin":"qǐchuáng","meaning_en":"to get up","meaning_ru":"вставать с кровати"},
    {"id":"2_082","hsk":2,"char":"起来","pinyin":"qǐlai","meaning_en":"to get up; to rise","meaning_ru":"вставать; подниматься"},
    {"id":"2_083","hsk":2,"char":"千","pinyin":"qiān","meaning_en":"thousand","meaning_ru":"тысяча"},
    {"id":"2_084","hsk":2,"char":"铅笔","pinyin":"qiānbǐ","meaning_en":"pencil","meaning_ru":"карандаш"},
    {"id":"2_085","hsk":2,"char":"晴","pinyin":"qíng","meaning_en":"clear (weather)","meaning_ru":"ясный (погода)"},
    {"id":"2_086","hsk":2,"char":"让","pinyin":"ràng","meaning_en":"to let; to allow","meaning_ru":"разрешать; позволять"},
    {"id":"2_087","hsk":2,"char":"日","pinyin":"rì","meaning_en":"day; date","meaning_ru":"день; дата"},
    {"id":"2_088","hsk":2,"char":"如果","pinyin":"rúguǒ","meaning_en":"if","meaning_ru":"если"},
    {"id":"2_089","hsk":2,"char":"身体","pinyin":"shēntǐ","meaning_en":"body; health","meaning_ru":"тело; здоровье"},
    {"id":"2_090","hsk":2,"char":"生病","pinyin":"shēngbìng","meaning_en":"to get sick","meaning_ru":"заболеть"},
    {"id":"2_091","hsk":2,"char":"生日","pinyin":"shēngrì","meaning_en":"birthday","meaning_ru":"день рождения"},
    {"id":"2_092","hsk":2,"char":"时间","pinyin":"shíjiān","meaning_en":"time","meaning_ru":"время"},
    {"id":"2_093","hsk":2,"char":"事情","pinyin":"shìqing","meaning_en":"matter; thing","meaning_ru":"дело; вещь"},
    {"id":"2_094","hsk":2,"char":"手表","pinyin":"shǒubiǎo","meaning_en":"watch","meaning_ru":"наручные часы"},
    {"id":"2_095","hsk":2,"char":"手机","pinyin":"shǒujī","meaning_en":"mobile phone","meaning_ru":"мобильный телефон"},
    {"id":"2_096","hsk":2,"char":"叔叔","pinyin":"shūshu","meaning_en":"uncle","meaning_ru":"дядя"},
    {"id":"2_097","hsk":2,"char":"送","pinyin":"sòng","meaning_en":"to send; to give as gift","meaning_ru":"отправлять; дарить"},
    {"id":"2_098","hsk":2,"char":"虽然","pinyin":"suīrán","meaning_en":"although; even though","meaning_ru":"хотя; несмотря на"},
    {"id":"2_099","hsk":2,"char":"它","pinyin":"tā","meaning_en":"it","meaning_ru":"оно; он/она (о вещах)"},
    {"id":"2_100","hsk":2,"char":"踢足球","pinyin":"tī zúqiú","meaning_en":"to play soccer","meaning_ru":"играть в футбол"},
    {"id":"2_101","hsk":2,"char":"题","pinyin":"tí","meaning_en":"question; topic","meaning_ru":"вопрос; тема"},
    {"id":"2_102","hsk":2,"char":"跳舞","pinyin":"tiàowǔ","meaning_en":"to dance","meaning_ru":"танцевать"},
    {"id":"2_103","hsk":2,"char":"外","pinyin":"wài","meaning_en":"outside; foreign","meaning_ru":"снаружи; иностранный"},
    {"id":"2_104","hsk":2,"char":"完","pinyin":"wán","meaning_en":"finished; to finish","meaning_ru":"закончить; закончился"},
    {"id":"2_105","hsk":2,"char":"玩","pinyin":"wán","meaning_en":"to play","meaning_ru":"играть"},
    {"id":"2_106","hsk":2,"char":"晚上","pinyin":"wǎnshang","meaning_en":"evening; night","meaning_ru":"вечер; ночь"},
    {"id":"2_107","hsk":2,"char":"往","pinyin":"wǎng","meaning_en":"towards","meaning_ru":"в направлении"},
    {"id":"2_108","hsk":2,"char":"为什么","pinyin":"wèishénme","meaning_en":"why","meaning_ru":"почему"},
    {"id":"2_109","hsk":2,"char":"问","pinyin":"wèn","meaning_en":"to ask","meaning_ru":"спрашивать"},
    {"id":"2_110","hsk":2,"char":"问题","pinyin":"wèntí","meaning_en":"question; problem","meaning_ru":"вопрос; проблема"},
    {"id":"2_111","hsk":2,"char":"西瓜","pinyin":"xīguā","meaning_en":"watermelon","meaning_ru":"арбуз"},
    {"id":"2_112","hsk":2,"char":"希望","pinyin":"xīwàng","meaning_en":"to hope; hope","meaning_ru":"надеяться; надежда"},
    {"id":"2_113","hsk":2,"char":"洗","pinyin":"xǐ","meaning_en":"to wash","meaning_ru":"мыть; стирать"},
    {"id":"2_114","hsk":2,"char":"笑","pinyin":"xiào","meaning_en":"to laugh; to smile","meaning_ru":"смеяться; улыбаться"},
    {"id":"2_115","hsk":2,"char":"新","pinyin":"xīn","meaning_en":"new","meaning_ru":"новый"},
    {"id":"2_116","hsk":2,"char":"姓","pinyin":"xìng","meaning_en":"surname; to be surnamed","meaning_ru":"фамилия; иметь фамилию"},
    {"id":"2_117","hsk":2,"char":"休息","pinyin":"xiūxi","meaning_en":"to rest","meaning_ru":"отдыхать"},
    {"id":"2_118","hsk":2,"char":"雪","pinyin":"xuě","meaning_en":"snow","meaning_ru":"снег"},
    {"id":"2_119","hsk":2,"char":"颜色","pinyin":"yánsè","meaning_en":"color","meaning_ru":"цвет"},
    {"id":"2_120","hsk":2,"char":"眼睛","pinyin":"yǎnjing","meaning_en":"eyes","meaning_ru":"глаза"},
    {"id":"2_121","hsk":2,"char":"要","pinyin":"yào","meaning_en":"to want; will","meaning_ru":"хотеть; будет"},
    {"id":"2_122","hsk":2,"char":"也","pinyin":"yě","meaning_en":"also; too","meaning_ru":"тоже; также"},
    {"id":"2_123","hsk":2,"char":"一起","pinyin":"yīqǐ","meaning_en":"together","meaning_ru":"вместе"},
    {"id":"2_124","hsk":2,"char":"一样","pinyin":"yīyàng","meaning_en":"same; alike","meaning_ru":"одинаковый; так же"},
    {"id":"2_125","hsk":2,"char":"已经","pinyin":"yǐjīng","meaning_en":"already","meaning_ru":"уже"},
    {"id":"2_126","hsk":2,"char":"因为","pinyin":"yīnwèi","meaning_en":"because","meaning_ru":"потому что"},
    {"id":"2_127","hsk":2,"char":"游泳","pinyin":"yóuyǒng","meaning_en":"to swim","meaning_ru":"плавать"},
    {"id":"2_128","hsk":2,"char":"右边","pinyin":"yòubiān","meaning_en":"right side","meaning_ru":"правая сторона"},
    {"id":"2_129","hsk":2,"char":"鱼","pinyin":"yú","meaning_en":"fish","meaning_ru":"рыба"},
    {"id":"2_130","hsk":2,"char":"远","pinyin":"yuǎn","meaning_en":"far; distant","meaning_ru":"далеко; далёкий"},
    {"id":"2_131","hsk":2,"char":"运动","pinyin":"yùndòng","meaning_en":"sport; exercise","meaning_ru":"спорт; упражнение"},
    {"id":"2_132","hsk":2,"char":"再","pinyin":"zài","meaning_en":"again","meaning_ru":"снова; ещё раз"},
    {"id":"2_133","hsk":2,"char":"早上","pinyin":"zǎoshang","meaning_en":"morning","meaning_ru":"утро"},
    {"id":"2_134","hsk":2,"char":"丈夫","pinyin":"zhàngfu","meaning_en":"husband","meaning_ru":"муж"},
    {"id":"2_135","hsk":2,"char":"找","pinyin":"zhǎo","meaning_en":"to look for; to find","meaning_ru":"искать; находить"},
    {"id":"2_136","hsk":2,"char":"着","pinyin":"zhe","meaning_en":"(continuous aspect particle)","meaning_ru":"(частица продолжительного действия)"},
    {"id":"2_137","hsk":2,"char":"真","pinyin":"zhēn","meaning_en":"really; true","meaning_ru":"действительно; настоящий"},
    {"id":"2_138","hsk":2,"char":"正在","pinyin":"zhèngzài","meaning_en":"in the process of","meaning_ru":"в процессе; сейчас"},
    {"id":"2_139","hsk":2,"char":"知道","pinyin":"zhīdào","meaning_en":"to know","meaning_ru":"знать"},
    {"id":"2_140","hsk":2,"char":"准备","pinyin":"zhǔnbèi","meaning_en":"to prepare","meaning_ru":"готовиться"},
    {"id":"2_141","hsk":2,"char":"走","pinyin":"zǒu","meaning_en":"to walk; to go","meaning_ru":"идти; ходить"},
    {"id":"2_142","hsk":2,"char":"最","pinyin":"zuì","meaning_en":"most","meaning_ru":"самый"},
    {"id":"2_143","hsk":2,"char":"左边","pinyin":"zuǒbiān","meaning_en":"left side","meaning_ru":"левая сторона"},
    {"id":"2_144","hsk":2,"char":"作业","pinyin":"zuòyè","meaning_en":"homework","meaning_ru":"домашнее задание"},
    {"id":"2_145","hsk":2,"char":"坐","pinyin":"zuò","meaning_en":"to sit","meaning_ru":"сидеть"},
    {"id":"2_146","hsk":2,"char":"下","pinyin":"xià","meaning_en":"down; below; next","meaning_ru":"вниз; под; следующий"},
    {"id":"2_147","hsk":2,"char":"先","pinyin":"xiān","meaning_en":"first; in advance","meaning_ru":"сначала; заранее"},
    {"id":"2_148","hsk":2,"char":"回来","pinyin":"huílai","meaning_en":"to come back","meaning_ru":"вернуться"},
    {"id":"2_149","hsk":2,"char":"出来","pinyin":"chūlai","meaning_en":"to come out","meaning_ru":"выйти; появиться"},
    {"id":"2_150","hsk":2,"char":"上来","pinyin":"shànglai","meaning_en":"to come up","meaning_ru":"подняться"},

    # ── HSK 3 (300 words — representative selection shown) ─────────────────
    {"id":"3_001","hsk":3,"char":"阿姨","pinyin":"āyí","meaning_en":"aunt; auntie","meaning_ru":"тётя"},
    {"id":"3_002","hsk":3,"char":"矮","pinyin":"ǎi","meaning_en":"short (height)","meaning_ru":"низкий (рост)"},
    {"id":"3_003","hsk":3,"char":"安静","pinyin":"ānjìng","meaning_en":"quiet; peaceful","meaning_ru":"тихий; спокойный"},
    {"id":"3_004","hsk":3,"char":"把","pinyin":"bǎ","meaning_en":"(disposal particle)","meaning_ru":"(частица диспозиции)"},
    {"id":"3_005","hsk":3,"char":"班","pinyin":"bān","meaning_en":"class; shift","meaning_ru":"класс; смена"},
    {"id":"3_006","hsk":3,"char":"搬","pinyin":"bān","meaning_en":"to move (objects)","meaning_ru":"переносить; перевозить"},
    {"id":"3_007","hsk":3,"char":"办法","pinyin":"bànfǎ","meaning_en":"method; way","meaning_ru":"метод; способ"},
    {"id":"3_008","hsk":3,"char":"办公室","pinyin":"bàngōngshì","meaning_en":"office","meaning_ru":"офис; кабинет"},
    {"id":"3_009","hsk":3,"char":"半","pinyin":"bàn","meaning_en":"half","meaning_ru":"половина"},
    {"id":"3_010","hsk":3,"char":"帮","pinyin":"bāng","meaning_en":"to help","meaning_ru":"помогать"},
    {"id":"3_011","hsk":3,"char":"包","pinyin":"bāo","meaning_en":"bag; to wrap","meaning_ru":"сумка; заворачивать"},
    {"id":"3_012","hsk":3,"char":"饱","pinyin":"bǎo","meaning_en":"full (after eating)","meaning_ru":"сытый"},
    {"id":"3_013","hsk":3,"char":"北","pinyin":"běi","meaning_en":"north","meaning_ru":"север"},
    {"id":"3_014","hsk":3,"char":"被","pinyin":"bèi","meaning_en":"(passive particle)","meaning_ru":"(пассивная частица)"},
    {"id":"3_015","hsk":3,"char":"鼻子","pinyin":"bízi","meaning_en":"nose","meaning_ru":"нос"},
    {"id":"3_016","hsk":3,"char":"必须","pinyin":"bìxū","meaning_en":"must; have to","meaning_ru":"должен; необходимо"},
    {"id":"3_017","hsk":3,"char":"变化","pinyin":"biànhuà","meaning_en":"change","meaning_ru":"изменение"},
    {"id":"3_018","hsk":3,"char":"表示","pinyin":"biǎoshì","meaning_en":"to express; to indicate","meaning_ru":"выражать; указывать"},
    {"id":"3_019","hsk":3,"char":"表演","pinyin":"biǎoyǎn","meaning_en":"to perform; performance","meaning_ru":"выступать; выступление"},
    {"id":"3_020","hsk":3,"char":"冰箱","pinyin":"bīngxiāng","meaning_en":"refrigerator","meaning_ru":"холодильник"},
    {"id":"3_021","hsk":3,"char":"不但","pinyin":"bùdàn","meaning_en":"not only","meaning_ru":"не только"},
    {"id":"3_022","hsk":3,"char":"才","pinyin":"cái","meaning_en":"only then; just","meaning_ru":"только тогда; лишь"},
    {"id":"3_023","hsk":3,"char":"参加","pinyin":"cānjiā","meaning_en":"to participate","meaning_ru":"участвовать"},
    {"id":"3_024","hsk":3,"char":"草","pinyin":"cǎo","meaning_en":"grass","meaning_ru":"трава"},
    {"id":"3_025","hsk":3,"char":"层","pinyin":"céng","meaning_en":"floor; layer","meaning_ru":"этаж; слой"},
    {"id":"3_026","hsk":3,"char":"差","pinyin":"chà","meaning_en":"poor; lacking","meaning_ru":"плохой; не хватает"},
    {"id":"3_027","hsk":3,"char":"超市","pinyin":"chāoshì","meaning_en":"supermarket","meaning_ru":"супермаркет"},
    {"id":"3_028","hsk":3,"char":"成绩","pinyin":"chéngjì","meaning_en":"grades; results","meaning_ru":"оценки; результаты"},
    {"id":"3_029","hsk":3,"char":"城市","pinyin":"chéngshì","meaning_en":"city","meaning_ru":"город"},
    {"id":"3_030","hsk":3,"char":"迟到","pinyin":"chídào","meaning_en":"to be late","meaning_ru":"опаздывать"},
    {"id":"3_031","hsk":3,"char":"船","pinyin":"chuán","meaning_en":"boat; ship","meaning_ru":"лодка; корабль"},
    {"id":"3_032","hsk":3,"char":"春","pinyin":"chūn","meaning_en":"spring (season)","meaning_ru":"весна"},
    {"id":"3_033","hsk":3,"char":"聪明","pinyin":"cōngming","meaning_en":"clever; smart","meaning_ru":"умный; сообразительный"},
    {"id":"3_034","hsk":3,"char":"打扫","pinyin":"dǎsǎo","meaning_en":"to clean; to sweep","meaning_ru":"убирать; подметать"},
    {"id":"3_035","hsk":3,"char":"打算","pinyin":"dǎsuàn","meaning_en":"to plan; to intend","meaning_ru":"планировать; намереваться"},
    {"id":"3_036","hsk":3,"char":"带","pinyin":"dài","meaning_en":"to bring; to take","meaning_ru":"брать с собой; приносить"},
    {"id":"3_037","hsk":3,"char":"担心","pinyin":"dānxīn","meaning_en":"to worry","meaning_ru":"беспокоиться"},
    {"id":"3_038","hsk":3,"char":"蛋糕","pinyin":"dàngāo","meaning_en":"cake","meaning_ru":"торт"},
    {"id":"3_039","hsk":3,"char":"当然","pinyin":"dāngrán","meaning_en":"of course","meaning_ru":"конечно"},
    {"id":"3_040","hsk":3,"char":"灯","pinyin":"dēng","meaning_en":"lamp; light","meaning_ru":"лампа; свет"},
    {"id":"3_041","hsk":3,"char":"地","pinyin":"de","meaning_en":"(adverbial particle)","meaning_ru":"(наречная частица)"},
    {"id":"3_042","hsk":3,"char":"地铁","pinyin":"dìtiě","meaning_en":"subway; metro","meaning_ru":"метро"},
    {"id":"3_043","hsk":3,"char":"地图","pinyin":"dìtú","meaning_en":"map","meaning_ru":"карта"},
    {"id":"3_044","hsk":3,"char":"电梯","pinyin":"diàntī","meaning_en":"elevator","meaning_ru":"лифт"},
    {"id":"3_045","hsk":3,"char":"东","pinyin":"dōng","meaning_en":"east","meaning_ru":"восток"},
    {"id":"3_046","hsk":3,"char":"冬","pinyin":"dōng","meaning_en":"winter","meaning_ru":"зима"},
    {"id":"3_047","hsk":3,"char":"动物","pinyin":"dòngwù","meaning_en":"animal","meaning_ru":"животное"},
    {"id":"3_048","hsk":3,"char":"段","pinyin":"duàn","meaning_en":"paragraph; section","meaning_ru":"абзац; отрезок"},
    {"id":"3_049","hsk":3,"char":"锻炼","pinyin":"duànliàn","meaning_en":"to exercise","meaning_ru":"тренироваться"},
    {"id":"3_050","hsk":3,"char":"多么","pinyin":"duōme","meaning_en":"how (exclamatory)","meaning_ru":"как; насколько (восклицание)"},

    # ── HSK 4 (600 words — key selection) ─────────────────────────────────
    {"id":"4_001","hsk":4,"char":"爱好","pinyin":"àihào","meaning_en":"hobby; interest","meaning_ru":"хобби; увлечение"},
    {"id":"4_002","hsk":4,"char":"安排","pinyin":"ānpái","meaning_en":"to arrange; arrangement","meaning_ru":"организовывать; распорядок"},
    {"id":"4_003","hsk":4,"char":"按时","pinyin":"ànshí","meaning_en":"on time","meaning_ru":"вовремя"},
    {"id":"4_004","hsk":4,"char":"百分之","pinyin":"bǎifēnzhī","meaning_en":"percent","meaning_ru":"процент"},
    {"id":"4_005","hsk":4,"char":"保护","pinyin":"bǎohù","meaning_en":"to protect","meaning_ru":"защищать; охранять"},
    {"id":"4_006","hsk":4,"char":"保证","pinyin":"bǎozhèng","meaning_en":"to guarantee","meaning_ru":"гарантировать"},
    {"id":"4_007","hsk":4,"char":"报道","pinyin":"bàodào","meaning_en":"to report; news report","meaning_ru":"репортаж; сообщать"},
    {"id":"4_008","hsk":4,"char":"倍","pinyin":"bèi","meaning_en":"times; -fold","meaning_ru":"раз (кратность)"},
    {"id":"4_009","hsk":4,"char":"本来","pinyin":"běnlái","meaning_en":"originally","meaning_ru":"изначально"},
    {"id":"4_010","hsk":4,"char":"笔记本","pinyin":"bǐjìběn","meaning_en":"notebook","meaning_ru":"тетрадь; ноутбук"},
    {"id":"4_011","hsk":4,"char":"毕业","pinyin":"bìyè","meaning_en":"to graduate","meaning_ru":"окончить учёбу"},
    {"id":"4_012","hsk":4,"char":"标准","pinyin":"biāozhǔn","meaning_en":"standard; criterion","meaning_ru":"стандарт; критерий"},
    {"id":"4_013","hsk":4,"char":"表格","pinyin":"biǎogé","meaning_en":"form; table","meaning_ru":"бланк; таблица"},
    {"id":"4_014","hsk":4,"char":"部分","pinyin":"bùfen","meaning_en":"part; section","meaning_ru":"часть; раздел"},
    {"id":"4_015","hsk":4,"char":"不管","pinyin":"bùguǎn","meaning_en":"no matter; regardless","meaning_ru":"независимо от"},
    {"id":"4_016","hsk":4,"char":"不得不","pinyin":"bùdébù","meaning_en":"have no choice but to","meaning_ru":"вынужден; не можешь не"},
    {"id":"4_017","hsk":4,"char":"不过","pinyin":"búguò","meaning_en":"however; but","meaning_ru":"однако; но"},
    {"id":"4_018","hsk":4,"char":"材料","pinyin":"cáiliào","meaning_en":"material; data","meaning_ru":"материал; данные"},
    {"id":"4_019","hsk":4,"char":"采访","pinyin":"cǎifǎng","meaning_en":"to interview","meaning_ru":"брать интервью"},
    {"id":"4_020","hsk":4,"char":"产品","pinyin":"chǎnpǐn","meaning_en":"product","meaning_ru":"продукт; товар"},
    {"id":"4_021","hsk":4,"char":"长城","pinyin":"Chángchéng","meaning_en":"the Great Wall","meaning_ru":"Великая стена"},
    {"id":"4_022","hsk":4,"char":"成功","pinyin":"chénggōng","meaning_en":"to succeed; success","meaning_ru":"успех; успешный"},
    {"id":"4_023","hsk":4,"char":"诚实","pinyin":"chéngshí","meaning_en":"honest; sincere","meaning_ru":"честный; искренний"},
    {"id":"4_024","hsk":4,"char":"吃惊","pinyin":"chījīng","meaning_en":"to be surprised","meaning_ru":"удивиться; быть поражённым"},
    {"id":"4_025","hsk":4,"char":"重新","pinyin":"chóngxīn","meaning_en":"again; anew","meaning_ru":"заново; снова"},

    # ── HSK 5 (1300 words — key selection) ────────────────────────────────
    {"id":"5_001","hsk":5,"char":"爱护","pinyin":"àihù","meaning_en":"to cherish; to take care of","meaning_ru":"беречь; заботиться"},
    {"id":"5_002","hsk":5,"char":"爱惜","pinyin":"àixī","meaning_en":"to treasure; to value","meaning_ru":"ценить; дорожить"},
    {"id":"5_003","hsk":5,"char":"安慰","pinyin":"ānwèi","meaning_en":"to comfort; to console","meaning_ru":"утешать"},
    {"id":"5_004","hsk":5,"char":"熬夜","pinyin":"áoyè","meaning_en":"to stay up late","meaning_ru":"не спать допоздна"},
    {"id":"5_005","hsk":5,"char":"把握","pinyin":"bǎwò","meaning_en":"to grasp; confidence","meaning_ru":"уверенность; схватить"},
    {"id":"5_006","hsk":5,"char":"摆","pinyin":"bǎi","meaning_en":"to place; to put","meaning_ru":"ставить; расставлять"},
    {"id":"5_007","hsk":5,"char":"颁布","pinyin":"bānbù","meaning_en":"to promulgate; to issue","meaning_ru":"обнародовать; издавать"},
    {"id":"5_008","hsk":5,"char":"悲观","pinyin":"bēiguān","meaning_en":"pessimistic","meaning_ru":"пессимистичный"},
    {"id":"5_009","hsk":5,"char":"本质","pinyin":"běnzhì","meaning_en":"essence; nature","meaning_ru":"сущность; природа"},
    {"id":"5_010","hsk":5,"char":"彼此","pinyin":"bǐcǐ","meaning_en":"each other; mutual","meaning_ru":"друг друга; взаимный"},
    {"id":"5_011","hsk":5,"char":"逼","pinyin":"bī","meaning_en":"to force; to compel","meaning_ru":"вынуждать; принуждать"},
    {"id":"5_012","hsk":5,"char":"避免","pinyin":"bìmiǎn","meaning_en":"to avoid","meaning_ru":"избегать"},
    {"id":"5_013","hsk":5,"char":"编辑","pinyin":"biānjí","meaning_en":"editor; to edit","meaning_ru":"редактор; редактировать"},
    {"id":"5_014","hsk":5,"char":"辩论","pinyin":"biànlùn","meaning_en":"to debate","meaning_ru":"дискутировать; дебаты"},
    {"id":"5_015","hsk":5,"char":"补充","pinyin":"bǔchōng","meaning_en":"to supplement; to add","meaning_ru":"дополнять; добавлять"},
    {"id":"5_016","hsk":5,"char":"不断","pinyin":"búduàn","meaning_en":"continuously; constantly","meaning_ru":"постоянно; непрерывно"},
    {"id":"5_017","hsk":5,"char":"不足","pinyin":"bùzú","meaning_en":"insufficient; inadequate","meaning_ru":"недостаточный"},
    {"id":"5_018","hsk":5,"char":"财富","pinyin":"cáifù","meaning_en":"wealth; fortune","meaning_ru":"богатство; состояние"},
    {"id":"5_019","hsk":5,"char":"策略","pinyin":"cèlüè","meaning_en":"strategy; tactics","meaning_ru":"стратегия; тактика"},
    {"id":"5_020","hsk":5,"char":"差异","pinyin":"chāyì","meaning_en":"difference; discrepancy","meaning_ru":"различие; расхождение"},
    {"id":"5_021","hsk":5,"char":"超过","pinyin":"chāoguò","meaning_en":"to exceed; to surpass","meaning_ru":"превышать; превосходить"},
    {"id":"5_022","hsk":5,"char":"承担","pinyin":"chéngdān","meaning_en":"to bear; to undertake","meaning_ru":"брать на себя; нести"},
    {"id":"5_023","hsk":5,"char":"充分","pinyin":"chōngfèn","meaning_en":"sufficient; full","meaning_ru":"достаточный; полный"},
    {"id":"5_024","hsk":5,"char":"创造","pinyin":"chuàngzào","meaning_en":"to create","meaning_ru":"создавать; творить"},
    {"id":"5_025","hsk":5,"char":"此外","pinyin":"cǐwài","meaning_en":"besides; moreover","meaning_ru":"кроме того; помимо"},

    # ── HSK 6 (2500 additional words — key selection) ──────────────────────
    {"id":"6_001","hsk":6,"char":"哀悼","pinyin":"āidào","meaning_en":"to mourn","meaning_ru":"скорбеть; оплакивать"},
    {"id":"6_002","hsk":6,"char":"暧昧","pinyin":"àimèi","meaning_en":"ambiguous; vague","meaning_ru":"двусмысленный; уклончивый"},
    {"id":"6_003","hsk":6,"char":"按照","pinyin":"ànzhào","meaning_en":"according to","meaning_ru":"согласно; в соответствии с"},
    {"id":"6_004","hsk":6,"char":"傲慢","pinyin":"àomàn","meaning_en":"arrogant; haughty","meaning_ru":"высокомерный; заносчивый"},
    {"id":"6_005","hsk":6,"char":"巴不得","pinyin":"bābude","meaning_en":"to eagerly wish","meaning_ru":"страстно желать"},
    {"id":"6_006","hsk":6,"char":"白费","pinyin":"báifèi","meaning_en":"to waste (effort)","meaning_ru":"тратить впустую"},
    {"id":"6_007","hsk":6,"char":"班子","pinyin":"bānzi","meaning_en":"team; troupe","meaning_ru":"команда; труппа"},
    {"id":"6_008","hsk":6,"char":"颁奖","pinyin":"bānjiǎng","meaning_en":"to award a prize","meaning_ru":"вручать награду"},
    {"id":"6_009","hsk":6,"char":"暴力","pinyin":"bàolì","meaning_en":"violence","meaning_ru":"насилие"},
    {"id":"6_010","hsk":6,"char":"悲剧","pinyin":"bēijù","meaning_en":"tragedy","meaning_ru":"трагедия"},
    {"id":"6_011","hsk":6,"char":"辩证","pinyin":"biànzhèng","meaning_en":"dialectical","meaning_ru":"диалектический"},
    {"id":"6_012","hsk":6,"char":"标志","pinyin":"biāozhì","meaning_en":"sign; symbol; mark","meaning_ru":"знак; символ"},
    {"id":"6_013","hsk":6,"char":"波动","pinyin":"bōdòng","meaning_en":"fluctuation; to fluctuate","meaning_ru":"колебание; колебаться"},
    {"id":"6_014","hsk":6,"char":"博大","pinyin":"bódà","meaning_en":"broad; extensive","meaning_ru":"широкий; обширный"},
    {"id":"6_015","hsk":6,"char":"不妨","pinyin":"bùfáng","meaning_en":"might as well; no harm in","meaning_ru":"не мешает; можно попробовать"},
    {"id":"6_016","hsk":6,"char":"裁判","pinyin":"cáipàn","meaning_en":"referee; judge","meaning_ru":"судья; арбитр"},
    {"id":"6_017","hsk":6,"char":"惨","pinyin":"cǎn","meaning_en":"tragic; miserable","meaning_ru":"трагичный; ужасный"},
    {"id":"6_018","hsk":6,"char":"层次","pinyin":"céngcì","meaning_en":"level; hierarchy","meaning_ru":"уровень; иерархия"},
    {"id":"6_019","hsk":6,"char":"阐述","pinyin":"chǎnshù","meaning_en":"to elaborate; to expound","meaning_ru":"излагать; разъяснять"},
    {"id":"6_020","hsk":6,"char":"超越","pinyin":"chāoyuè","meaning_en":"to transcend; to surpass","meaning_ru":"превосходить; выходить за рамки"},
    {"id":"6_021","hsk":6,"char":"沉默","pinyin":"chénmò","meaning_en":"silence; silent","meaning_ru":"молчание; молчать"},
    {"id":"6_022","hsk":6,"char":"陈述","pinyin":"chénshù","meaning_en":"to state; to narrate","meaning_ru":"излагать; описывать"},
    {"id":"6_023","hsk":6,"char":"诚信","pinyin":"chéngxìn","meaning_en":"integrity; good faith","meaning_ru":"честность; добросовестность"},
    {"id":"6_024","hsk":6,"char":"持续","pinyin":"chíxù","meaning_en":"to continue; sustainable","meaning_ru":"продолжать; устойчивый"},
    {"id":"6_025","hsk":6,"char":"冲突","pinyin":"chōngtū","meaning_en":"conflict; clash","meaning_ru":"конфликт; столкновение"},
]
